---
apiVersion: v1
kind: Namespace
metadata:
  name: kiii-proekt
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kiii-proekt-pv
  namespace: kiii-proekt
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/kiii-proekt
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiii-proekt-pvc
  namespace: kiii-proekt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiii-proekt-db-configmap
  namespace: kiii-proekt
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "12345"
  POSTGRES_DB: "kiii-proekt-db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiii-proekt-app-configmap
  namespace: kiii-proekt
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://kiii-proekt-db-svc:5432/kiii-proekt-db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "12345"
---
apiVersion: v1
kind: Service
metadata:
  name: kiii-proekt-db-svc
  namespace: kiii-proekt
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 30002
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: kiii-proekt-app-svc
  namespace: kiii-proekt
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30001
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-proekt-db-deployment
  namespace: kiii-proekt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: kiii-proekt-db-configmap
          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: kiii-proekt-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-proekt-app-deployment
  namespace: kiii-proekt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-container
          image: dimitarjovanovski01/kiii-proekt-app:1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: kiii-proekt-app-configmap
