version: "3"

services:

    app:
      image: dimitarjovanovski01/kiii-proekt-app:1.0
      build:
        context: .
        dockerfile: Dockerfile
      container_name: kiii-app
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/kiii-proekt-db
      ports:
        - 8080:8080
      depends_on:
        - db

    db:
      image: postgres
      container_name: kiii-db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=12345
        - POSTGRES_DB=kiii-proekt-db
      ports:
        - 5432:5432
      volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
