apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-proekt-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: kiii-proekt-db-configmap
          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: kiii-proekt-pvc
