apiVersion: v1
kind: PersistentVolume
metadata:
    name: kiii-proekt-pv
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /data/kiii-proekt